// Copyright 2024 PARK Youngho.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your option.
// This file may not be copied, modified, or distributed
// except according to those terms.

//! # Introduction
//! The module that contains a few sub-modules to define various pseudo-random
//! number generators
//! 
//! # Background: Random number generators
//! 
//! 
//! # Three kinds of long bit integers
//! This module provides some kinds of pseudo-random number generators.
//! - `BigUInt` --- a big _unsigned_ integer with user-defined _fixed_ size. [Read more](struct@BigUInt)
//! - `BigSInt` --- a big _signed_ integer with user-defined _fixed_ size.
//! - `LargeInt` --- a big _signed_ integer with _variable_ size.
//! 
//! # Predefined big unsigned integer data types
//! There are provided predefined data types: `u256`, `u512`, `u1024`, `u2048`,
//! `u3072`, `u4096`, `u5120`, `u6144`, `u7168`, `u8192`, and `u16384`.
//! And their synonyms are also provided such as `U32` (= `u256`),
//! `U64` (= `u512`), `U128` (= `u1024`), `U256` (= `u2048`),
//! `U384` (= `u3072`), `U512` (= `u4096`), `U640` (= `u5120`),
//! `U768` (= `u6144`), `U896` (= `u7168`), `U1024` (= `u8192`),
//! and `U2048` (= `u16384`). You can further define more data types.
//! 
//! `u256` for 64-bit machines is `BigUInt<u64, 4>` for example
//! while `u256` for 32-bit machines is `BigUInt<u32, 8>` for example.
//! 
//! # Quality Issues and Debate
//! The pseudo-random number generators in this module use hash algorithms,
//! encrytion/decryption algorithms, etc. which are not originally designed
//! for pseudo-random number generator. At the Internet, you can find a lot of
//! research results in terms of the possibility to use hash algorithms and/or
//! encryption algorithms for a pseudo-random number generator. This module can
//! also be considered to be a part of the research.
//! 
//! Some people doubt the cryptographical security of the pseudo-random number
//! generator using hash algorithm and/or encryption algorithm though the
//! offical hash algorithms published by NIST such as SHA-3 and SHA-2 are known
//! to have passed all the statistical and cryptographical security tests,
//! which have been done from 2006 to 2015 for SHA-3 and from 2001 to 2012 for
//! SHA-2. The tests included collision attack, preimage attack, and
//! second-preimage attack. It means that a pseudo-random number generator that
//! uses a hash algorithm has the long enough period of its recursively[^note]
//! produced random numbers for most of the cases. According to
//! [security collision chart](https://en.wikipedia.org/wiki/SHA-3#Comparison_of_SHA_functions),
//! the security stregths against collision of SHA-3-512, SHA-3-256, SHA-2-512
//! and SHA-2-256 are 256 bits, 128 bits, 256 bits, and 128 bits, respectively,
//! because of
//! [birthday paradox or birthday problem](https://en.wikipedia.org/wiki/Birthday_problem).
//! So, the period of pseudo-random numbers which is hash values generated by
//! hash algorithms can be theoretically
//! '115792089237316195423570985008687907853269984665640564039457584007913129639935',
//! which is 2^256, for 512-bit hash values of SHA-3-512 and SHA-2-512, and
//! '340282366920938463463374607431768211455', which is 2^128, for 256-bit hash
//! values of SHA-3-256 and SHA-2-256. So, __for non-cryptographical
//! purposes,__ all the pseudo-random number generators in this module are
//! completely fine to use.
//! 
//! However, __for serious cryptographical purpose,__ it is still
//! debatable.
//! So, if you really want one of the best quality pseudo-random number
//! generator rather than this module for serious cryptographical purpose,
//! you are encouraged to use the crate
//! [rand::rngs::OsRng](https://docs.rs/rand/latest/rand/rngs/struct.OsRng.html)
//! which is well known to be a good pseudo-random number generator for
//! _cryptographical_ security purpose. The module of implementation of
//! `Random_Generic<GenFunc: PRNG + 'static>` to use
//! [rand::rngs::OsRng](https://docs.rs/rand/latest/rand/rngs/struct.OsRng.html)
//! as a pseudo-random number generator is not implemented in this crate in
//! order to keep small number of dependencies but how to make a module of
//! implementation of `Random_Generic<GenFunc: PRNG + 'static>`to use
//! [rand::rngs::OsRng](https://docs.rs/rand/latest/rand/rngs/struct.OsRng.html)
//! is shown below in the section 'HOW TO USE OsRng IN THIS MODULE' in order
//! to help you implement a module to use
//! [rand::rngs::OsRng](https://docs.rs/rand/latest/rand/rngs/struct.OsRng.html)
//! as a pseudo-random number generator in your project by yourself. 
//! 
//! # QUICK START
//! You can use either struct `Any` or `Random` depending on your purpose.
//! `Any` is for normal non-cryptographical purpose while `Random` is for
//! cryptographical purpose if you are fine to use hash algorithm for
//! pseudo-random number generator for cryptographical purpose. Look into
//! the following examples.
//! 
//! ## Example 1
//! ```
//! //Todo
//! ```
//! 
//! # HOW TO USE OsRng IN THIS MODULE
//! First, you have to include additional dependencies in your Cargo.toml
//! as follows.
//! 
//! ## Example 3
//! ```
//! [dependencies]
//! Cryptocol = "0.10"
//! rand = { version = "0.8", features = ["getrandom"] }
//! ```
//! It is good if you keep the version number of each crate as latest version.
//! 
//! Second, you need to make a new empty rust source file in proper folder.
//! Let's say the empty rust source file `trait_impl_for_OsRng.rs`. In the file
//! `trait_impl_for_OsRng.rs`, you have to import some `struct`s as follows.
//! 
//! ## Example 4
//! ```
//! use std::ops::*;
//! use std::fmt::{ Display, Debug };
//! use rand::{ rngs, RngCore };
//! use Cryptocol::number::SmallUInt;
//! use Cryptocol::random::{ PRNG, Random_Generic };
//! ```
//! 
//! Third, you have to make an empty struct `OsRng` as follows.
//! 
//! ## Example 5
//! ```
//! pub struct OsRng;
//! ```
//! 
//! Fourth, you are supposed to make implementation of trait PRNG for the
//! empty struct `OsRng` as follows.
//! 
//! ## Example 6
//! ```
//! impl PRNG for OsRng
//! {
//!     #[inline]
//!     fn new() -> Self    { Self }
//! 
//!     #[inline]
//!     fn new_with<T, const N: usize>(_: &[T; N]) -> Self
//!     where T: SmallUInt + Copy + Clone + Display + Debug + ToString
//!         + Add<Output=T> + AddAssign + Sub<Output=T> + SubAssign
//!         + Mul<Output=T> + MulAssign + Div<Output=T> + DivAssign
//!         + Rem<Output=T> + RemAssign
//!         + Shl<Output=T> + ShlAssign + Shr<Output=T> + ShrAssign
//!         + BitAnd<Output=T> + BitAndAssign + BitOr<Output=T> + BitOrAssign
//!         + BitXor<Output=T> + BitXorAssign + Not<Output=T>
//!         + PartialEq + PartialOrd
//!     { Self::new() }
//! 
//!     #[inline]
//!     fn sow_array<T, const N: usize>(&mut self, _: &[T; N])
//!     where T: SmallUInt + Copy + Clone + Display + Debug + ToString
//!         + Add<Output=T> + AddAssign + Sub<Output=T> + SubAssign
//!         + Mul<Output=T> + MulAssign + Div<Output=T> + DivAssign
//!         + Rem<Output=T> + RemAssign
//!         + Shl<Output=T> + ShlAssign + Shr<Output=T> + ShrAssign
//!         + BitAnd<Output=T> + BitAndAssign + BitOr<Output=T> + BitOrAssign
//!         + BitXor<Output=T> + BitXorAssign + Not<Output=T>
//!         + PartialEq + PartialOrd
//!     {}
//! 
//!     #[inline]
//!     fn harvest(&mut self, _: u64) -> [u64; 8]
//!     {
//!         [rngs::OsRng.next_u64(), rngs::OsRng.next_u64(),
//!         rngs::OsRng.next_u64(), rngs::OsRng.next_u64(),
//!         rngs::OsRng.next_u64(), rngs::OsRng.next_u64(),
//!         rngs::OsRng.next_u64(), rngs::OsRng.next_u64()]
//!     }
//! }
//! ```
//! 
//! Fifth, you have to define user-defined data type for your convenience
//! as follows.
//! 
//! ## Example 7
//! ```
//! pub type Random_OsRng = Random_Generic<OsRng>;
//! ```
//! 
//! Now, you are very ready to use `Random_OsRng` in your own project. And,
//! all the methods of Random_OsRng has been automagically implemented and
//! you can use them for free.
//! In other source file of your project, you have to import `Random_OsRng`.
//! In the following example, it is assumed that `trait_impl_for_OsRng.rs`
//! is placed in the same folder.
//! The following example shows how to use `Random_OsRng` in your project.
//! 
//! ## Example 8
//! ```
//! use super::trait_impl_for_OsRng::Random_OsRng;
//! 
//! let mut r = Random_OsRng::new();
//! println!("Random_OsRng u8 = {}", r.random_u8());
//! println!("Random_OsRng u16 = {}", r.random_u16());
//! println!("Random_OsRng u32 = {}", r.random_u32());
//! println!("Random_OsRng u64 = {}", r.random_u64());
//! println!("Random_OsRng u128 = {}", r.random_u128());
//! println!("Random_OsRng under 123456789 = {}", r.random_under_uint_(123456789_u64));
//! println!("Random_OsRng prime number = {}", r.random_prime_using_Miller_Rabin_uint::<u128>(5));
//! println!("Random_OsRng BigUInt = {}", r.random_BigUInt::<u64, 8>());
//! println!("Random_OsRng odd BigUInt = {}", r.random_odd_BigUInt::<u64, 8>());
//! println!("Random_OsRng BigUInt prime number = {}", r.random_prime_using_Miller_Rabin_BigUInt::<u64, 8>(5));
//! ```
//! 
//! 
//! For `Random_Generic`, read [here](struct@Random_Generic).
//! 
//! [^note]: Here, 'recursively' means that the output hash value of a hash
//! function is fed back to the hash function as its message, and a new hash
//! value is gotten from it, and then the new hash value is fed back to the
//! hash function as its message again, and this process is repeated.
//! 



pub mod random;
pub mod trait_prng;
pub mod trait_impl_for_MD4;
pub mod trait_impl_for_MD5;
pub mod trait_impl_for_SHA1;
pub mod trait_impl_for_SHA2_256;
pub mod trait_impl_for_SHA2_512;

pub use random::*;
pub use trait_prng::*;