[package]
name = "cryptocol"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A cryptographic library that includes big number operation, encoding algorithm, decoding algorithm, hash algorithm, etc but it is under development"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
incremental = false

[dependencies]
