[package]
authors = ["PARK Youngho"]
categories = ["algorithms", "cryptography", "mathematics"]
description = "A cryptographic library that includes big number arithmatic operation, Hash Algorithms, Symmetric-Key Cryptographic Algorithms, Asymmetric-Key Cryptographic Algorithms, Pseudo-random number generators, etc."
edition = "2021"
keywords = ["cryptography", "security", "encryption", "hash", "number"]
license = "MIT OR Apache-2.0"
name = "cryptocol"
readme = "README.md"
version = "0.6.0"
repository = "https://github.com/piaoyh/cryptocol"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
incremental = false

[dependencies]
#rand = { version = "0.8", features = ["getrandom"] }
#rand_chacha = "0.3.1"
#rand_distr = "0.4.3"
#rand_pcg = "0.3.1"
#rand_seeder = "0.2.3"
