[package]
name = "cryptocol"
version = "0.5.0"
authors = ["PARK Youngho"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A cryptographic library that includes big number arithmatic operation, Hash Algorithms, Symmetric-Key Cryptographic Algorithms, Asymmetric-Key Cryptographic Algorithms, Pseudo-random number generators, etc."
keywords = ["cryptography", "security", "encryption", "hash", "number"]
categories = ["algorithms", "cryptography", "mathematics"]
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
incremental = false

[dependencies]
#rand = { version = "0.8", features = ["getrandom"] }
#rand_chacha = "0.3.1"
#rand_distr = "0.4.3"
#rand_pcg = "0.3.1"
#rand_seeder = "0.2.3"
