// Copyright 2025 PARK Youngho.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your option.
// This file may not be copied, modified, or distributed
// except according to those terms.


#![allow(missing_docs)]
#![allow(unused_must_use)]
#![allow(dead_code)]
#![allow(unused_variables)]
// #![warn(rustdoc::missing_doc_code_examples)]



/// rsa.rs may be too big
/// because of documentation and plenty of examples.
/// So, in order to provide documentation without `docs.rs`'s failing
/// generating documentation, dummy codes were made and documentation and
/// examples were moved to rsa_basic.rs.
#[allow(non_camel_case_types)]
pub struct RSA_Generic<const N: usize, T, const MR: usize = 5>
where T: TraitsBigUInt<T>
{
    // Dummy struct for documentation
}

/// rsa.rs may be too big
/// because of documentation and plenty of examples.
/// So, in order to provide documentation without `docs.rs`'s failing
/// generating documentation, dummy codes were made and documentation and
/// examples were moved to rsa_basic.rs. And, most of generic parameters
/// are omitted. It is not actual code but dummy code for compilation!!!
impl<const N: usize, T, const MR: usize> RSA_Generic<N, T, MR>
where T: TraitsBigUInt<T>
{

    // pub fn new() -> Self
    /// Constructs a new object of the struct `RSA_Generic`.
    /// 
    /// # Output
    /// A new object of the struct `RSA_Generic` whose modulo, publick key and
    /// private key are all reset to be `zero`.
    /// 
    /// # Features
    /// Unless you set the modulo, the publick key and the private key to be
    /// proper values, you cannot use the object generated by this method.
    /// 
    /// # Example 1 for RSA_1024
    /// ```
    /// use cryptocol::asymmetric::RSA_1024;
    /// use cryptocol::define_utypes_with;
    /// define_utypes_with!(u128);
    /// 
    /// let rsa = RSA_1024::new();
    /// ```
    /// 
    /// # Example 2 for RSA_2048
    /// ```
    /// use cryptocol::asymmetric::RSA_2048;
    /// use cryptocol::define_utypes_with;
    /// define_utypes_with!(u128);
    /// 
    /// let rsa = RSA_2048::new();
    /// ```
    /// 
    /// # Example 3 for RSA_4096
    /// ```
    /// use cryptocol::asymmetric::RSA_4096;
    /// use cryptocol::define_utypes_with;
    /// define_utypes_with!(u128);
    /// 
    /// let rsa = RSA_4096::new();
    /// ```
    /// 
    /// # Example 4 for RSA_Genric
    /// ```
    /// use cryptocol::asymmetric::RSA_Genric;
    /// use cryptocol::define_utypes_with;
    /// define_utypes_with!(u128);
    /// 
    /// let rsa = RSA_Genric::new();
    /// ```
    pub fn new() -> Self
    {
        unimplemented!(); // Dummy code for documentation
    }
}